// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRlCpJAwhpnK4uIYrKoDTLrNw_EVsNdwM',
    appId: '1:684978459452:web:da3614d362d0424dbcc439',
    messagingSenderId: '684978459452',
    projectId: 'tiktokclone-8be16',
    authDomain: 'tiktokclone-8be16.firebaseapp.com',
    storageBucket: 'tiktokclone-8be16.appspot.com',
    measurementId: 'G-MMGNM2JL2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA24vK8Ru55cLSqc53z-z_ykm7Qpt4SEis',
    appId: '1:684978459452:android:b23ab53fe1ae4753bcc439',
    messagingSenderId: '684978459452',
    projectId: 'tiktokclone-8be16',
    storageBucket: 'tiktokclone-8be16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrUIEk3kQe9YNtcxmJdNWIlhrX7hRWdRs',
    appId: '1:684978459452:ios:7bcc1a8cf55bdbc4bcc439',
    messagingSenderId: '684978459452',
    projectId: 'tiktokclone-8be16',
    storageBucket: 'tiktokclone-8be16.appspot.com',
    iosClientId:
        '684978459452-e6c1o4oj1uu6dcjchg26e88afp032kf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrUIEk3kQe9YNtcxmJdNWIlhrX7hRWdRs',
    appId: '1:684978459452:ios:7bcc1a8cf55bdbc4bcc439',
    messagingSenderId: '684978459452',
    projectId: 'tiktokclone-8be16',
    storageBucket: 'tiktokclone-8be16.appspot.com',
    iosClientId:
        '684978459452-e6c1o4oj1uu6dcjchg26e88afp032kf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.clone',
  );
}
